### ISSUE TITLE
H-Pattern working in windows but not picking up any inputs in Linux (CachyOS)

### ISSUE THREAD

**Issue by markhagemann** [Lawstorant/boxflat#4]
Hey, thanks heaps for this package, it's really exciting to see. 

Everything has worked flawlessly so far except I'm not able to get any h-pattern inputs working. I initially thought it may have just been a problem with Dirt Rally 2 but even in Euro Truck Simulator 2 it wasn't picking up any of the inputs either.

Wondering if you have any advice / debugging tips? Happy to move this into a discussion rather than an issue.

Thanks!

**Comment by Lawstorant** [comment]
Hi! Thanks for using this project! It's really fullfiling to see it helps anyone beside me 😄 

Back to HhPatter though. Boxflat is only made to read and change Moza settings. It's not a driver. FFB is handled by universal-pidff and input is just Linux. Moza devices are plain USB HID devices.

Your shifter sadly won't work through the base at the moment. Linux has a limitation of 80 buttons for HID joysticks and h-pattern buttons are 112+.

To make it work you need to connect it through USB and use `protopedal` to force proton to pick it up. If you don't want to configure protopedal yourself, I made `protopedal-community-configs`. It'll set it up so hpatter will automatically show up in games running through proton.

**Comment by Lawstorant** [comment]
I'm actively pushing for linux maintainers to pick up my patch that increases this button limit, but it'll come in 6.11 at the earliest. For now, pprotopedal is a great piece of software

**Comment by Lawstorant** [comment]
@markhagemann hi! I just wanted to let you know that today I fixed this issue in the driver. I added manual button handling and now our driver handles up to 160 buttons. 

Moza only has 128, so everything should just work, without the need for hacks. You can uninstall protopedal and use your shifter through the base itself :)

**Comment by markhagemann** [comment]
That is awesome to know! I have been moving house so I've not been able to test any of your recent updates but hopefully this weekend I can :) thanks again for all the hard work.

**Comment by wolfallein** [comment]
Hi @Lawstorant Thank you for all the work you put into this project and `universal-pidff` driver.
I remember that at some point the 80 buttons limitation was fixed, but I'm running kernel 6.17.10 now, and I have 80 buttons limitation. H-pattern does not work when connected to the base.
I'm not sure if I got this problem when I started to use the upstreamed version.
Do you have any idea of a possible fix for this? Should I compile the driver instead of using the upstreamed version?

**Comment by Lawstorant** [comment]
Yes, seems like debian didn't bother to enable this driver. Someone should bug them about it.
If you want full functionality, installing with dkms is the best option for now

**Comment by writequit** [comment]
Thanks, I will do both of those things.

**Comment by Lawstorant** [comment]
I'll try as well since I'm the maintainer. Maybe It'll make it to debian 12 as well

**Comment by writequit** [comment]
According to debian bug #1122144 the hid-universal-pidff module will be included in linux 6.18.1-1~exp1. 

Currently in the archives I still see 6.18~rc7-1~exp1 but looks like it should release today.
